trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - src/LinuxGPIB.Demo/**
    include:
      - src/LinuxGPIB.Tests/**
      - src/LinuxGPIB.Net/**
      - LinuxGPIB.Net.sln

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: UnitTests
        displayName: Run unit tests
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            arguments: '--collect "Code coverage"'